apiVersion: v1
kind: Service
metadata:
  name: payment-service # This name becomes the internal DNS URL (http://payment-service:3002)
  namespace: healthbridge
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005