apiVersion: v1
kind: Secret
metadata:
  name: healthbridge-secrets
  namespace: healthbridge
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://HealthBridge_DB:Team_Health_Bridge_12@cluster0.d8ewy6i.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "super_secret_healthbridge_key_change_this_later"
  GROQ_API_KEY: "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"