apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: healthbridge
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 5007
      targetPort: 5007
  type: ClusterIP