apiVersion: v1
kind: Secret
metadata:
  name: telemedicine-secrets
  namespace: healthbridge
type: Opaque
stringData:
  AGORA_APP_ID: "b0cb8cb429cc4125a95924b2f96ea00a"
  AGORA_APP_CERTIFICATE: "300e0a2214a54e5a903ae1bf8a090e37"