apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
  namespace: healthbridge
spec:
  selector:
    app: telemedicine-service
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3008