apiVersion: v1
kind: Service
metadata:
  name: auth-service # This name becomes the internal DNS URL (http://auth-service:3001)
  namespace: healthbridge
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001