apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: healthbridge
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: docker-notification-service:latest # Uses your locally built Docker image
        imagePullPolicy: IfNotPresent     # Tells Kubernetes to use the local image instead of downloading
        ports:
        - containerPort: 3006
        env:
        - name: PORT
          value: "3006"
        - name: JWT_SECRET
          value: "super_secret_healthbridge_key_change_this_later"
        - name: MONGO_URI
          value: "mongodb+srv://HealthBridge_DB:Team_Health_Bridge_12@cluster0.d8ewy6i.mongodb.net/?appName=Cluster0"
        - name: MONGO_DB_NAME
          value: "healthbridge_notification_db"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: INTERNAL_SERVICE_SECRET
          value: "healthbridge_internal_secret"
        - name: ZOHO_CLIENT_ID
          value: "1000.R4X5OQO24U5CA6QPAL2VWS27OVQEQH"
        - name: ZOHO_CLIENT_SECRET
          value: "041528b84887cce0ac688759b0c6f63667f0079257"
        - name: ZOHO_ACCESS_TOKEN
          value: "1000.e713a6e751354869711045b79d47fde1.1f07ebf4da5afa33aa950c8926c661bf"
        - name: ZOHO_REFRESH_TOKEN
          value: "1000.f6548ad136cbaa23b3e97666be12af50.788352d8f843522106f269ebce5e8357"
        - name: ZOHO_ACCOUNT_ID
          value: "6144660000000008002"
        - name: ZOHO_EMAIL
          value: "no-reply@sjaywebsolutions.lk"
        - name: SMS_DRIVER
          value: "textlk"
        - name: TEXTLK_API_KEY
          value: "3687|q6pRAAWioGlYPEXaEKDLScXSOIeuwCDjurTRGNAL5814c9d8"
        - name: TEXTLK_SENDER_ID
          value: "OneX Team"
        - name: TEXTLK_URL
          value: "https://app.text.lk/api/v3/sms/send"