export const SPECIALIZATION = {
    CARDIOLOGY: 'Cardiology',
    DERMATOLOGY: 'Dermatology',
    NEUROLOGY: 'Neurology',
    PEDIATRICS: 'Pediatrics',
    ORTHOPEDICS: 'Orthopedics',
    PSYCHIATRY: 'Psychiatry',
    GYNECOLOGY: 'Gynecology',
    ONCOLOGY: 'Oncology',
    RADIOLOGY: 'Radiology',
    UROLOGY: 'Urology',
    ENDOCRINOLOGY: 'Endocrinology',
    GASTROENTEROLOGY: 'Gastroenterology',
    HEMATOLOGY: 'Hematology',
    INFECTIOUS_DISEASES: 'Infectious Diseases',
    NEPHROLOGY: 'Nephrology',
    PULMONOLOGY: 'Pulmonology',
    RHEUMATOLOGY: 'Rheumatology',
    ALLERGY_IMMUNOLOGY: 'Allergy & Immunology',
    ANESTHESIOLOGY: 'Anesthesiology',
    EMERGENCY_MEDICINE: 'Emergency Medicine',
    FAMILY_MEDICINE: 'Family Medicine',
    INTERNAL_MEDICINE: 'Internal Medicine',
    PATHOLOGY: 'Pathology',
    PHYSICAL_MEDICINE_REHABILITATION: 'Physical Medicine & Rehabilitation',
    PREVENTIVE_MEDICINE: 'Preventive Medicine',
    RADIOLOGY: 'Radiology',
    SURGERY: 'Surgery',
    OTHER: 'Other'
};