version: '3.8'

services:
  api-gateway:
    build: 
      context: ../api-gateway      
      dockerfile: Dockerfile
    container_name: healthbridge-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=super_secret_healthbridge_key_change_this_later
      - AUTH_SERVICE_URL=http://auth-service:3001 # Docker networking magic!
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ../            # Build from the root folder so it can see the 'shared' folder
      dockerfile: ./services/auth-service/Dockerfile
    container_name: healthbridge-auth
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET=super_secret_healthbridge_key_change_this_later
      # IMPORTANT: Use your actual MongoDB Atlas connection string here
      - MONGO_URI=mongodb+srv://HealthBridge_DB:Team_Health_Bridge_12@cluster0.d8ewy6i.mongodb.net/?appName=Cluster0
      - MONGO_DB_NAME=healthbridge_auth_db