apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: healthbridge
spec:
  type: ClusterIP # Kept internal because the Ingress will handle external traffic
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000